// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSkRHaakcFuCBfE42iioqFx9EXRerURE',
    appId: '1:454823228171:web:c32343ce4205478577680e',
    messagingSenderId: '454823228171',
    projectId: 'hello-athena',
    authDomain: 'hello-athena.firebaseapp.com',
    storageBucket: 'hello-athena.firebasestorage.app',
    measurementId: 'G-055YMMHM3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdu5G8lq4OJbNdN6zy1ubll0k-RXOODo',
    appId: '1:454823228171:android:4cf3f3673b6e58eb77680e',
    messagingSenderId: '454823228171',
    projectId: 'hello-athena',
    storageBucket: 'hello-athena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5bW8QdNRQ8LBZPBebwCmsOK91Rc1bj_g',
    appId: '1:454823228171:ios:aae57ee0b64af46077680e',
    messagingSenderId: '454823228171',
    projectId: 'hello-athena',
    storageBucket: 'hello-athena.firebasestorage.app',
    iosBundleId: 'app.helloathena.athena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5bW8QdNRQ8LBZPBebwCmsOK91Rc1bj_g',
    appId: '1:454823228171:ios:e1d6c516ff41649b77680e',
    messagingSenderId: '454823228171',
    projectId: 'hello-athena',
    storageBucket: 'hello-athena.firebasestorage.app',
    iosBundleId: 'com.example.athena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRSkRHaakcFuCBfE42iioqFx9EXRerURE',
    appId: '1:454823228171:web:88814edf3679f41877680e',
    messagingSenderId: '454823228171',
    projectId: 'hello-athena',
    authDomain: 'hello-athena.firebaseapp.com',
    storageBucket: 'hello-athena.firebasestorage.app',
    measurementId: 'G-99DXH4S6NR',
  );
}
