import 'package:athena/core/errors/failures.dart';
import 'package:athena/features/review/domain/entities/quiz_entity.dart';
import 'package:athena/features/review/domain/repositories/review_repository.dart';
import 'package:athena/features/review/domain/usecases/params/create_quiz_params.dart';
import 'package:dartz/dartz.dart';

class CreateQuizUseCase {
  final ReviewRepository _repository;

  CreateQuizUseCase(this._repository);

  Future<Either<Failure, QuizEntity>> call(
    CreateQuizParams params,
  ) {
    final quiz = QuizEntity(
      id: '', // ID will be generated by the database
      userId: params.userId,
      title: params.title,
      studyMaterialId: params.studyMaterialId,
      subject: params.subject,
      description: params.description,
      createdAt: DateTime.now(),  // Will be overridden by the database
      updatedAt: DateTime.now(),  // Will be overridden by the database
    );

    return _repository.createQuiz(quiz);
  }
}
